# Generated by Django 5.0.6 on 2024-07-14 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_report_delete_usersreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
