# Generated by Django 5.0.6 on 2024-07-16 12:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_report_report_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JunctionManholeElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(blank=True, max_length=255, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('valve_state', models.CharField(blank=True, max_length=255, null=True)),
                ('pump_state', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'junction_manhole_elements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pozzetti',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('grado', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('pozzetti_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'pozzetti',
                'managed': False,
            },
        ),
    ]
